services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY_CHATBOT_BACKEND}
    restart: unless-stopped
